/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tecmis;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.List;
import java.util.Vector;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KA VI YA
 */
public class StudentDashboard extends javax.swing.JFrame {

   Connection conn1=ConnectDB.MyDBConnection();
   NumberFormat formatter = new DecimalFormat("#0.00");
    private static DecimalFormat df = new DecimalFormat("0.00");     

    /**
     * Creates new form StudentDashboard
     */
    private static String userID;
    private static String gettDepID;
    private static String Level;
    private static String tSem;
    private static String Subject_code;
    private static String CA_Status;
    private static String Grade;
    private static double GPA;
   // private static String SEVERE;

    PreparedStatement insert;
    PreparedStatement update;
    PreparedStatement CID;
    CardLayout cardLayout1;

    public StudentDashboard() {
        initComponents();
        cardLayout1 = (CardLayout)(StuPnnel.getLayout());
        
   }
    public String getUser() {
        return userID;
    }

    public void setUser(String aUser) {
        userID = aUser;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        adName = new javax.swing.JLabel();
        menutimetable = new rojerusan.RSMaterialButtonRectangle();
        menuuser = new rojerusan.RSMaterialButtonRectangle();
        menucourse = new rojerusan.RSMaterialButtonRectangle();
        menunotice = new rojerusan.RSMaterialButtonRectangle();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        menutimetable1 = new rojerusan.RSMaterialButtonRectangle();
        menutimetable2 = new rojerusan.RSMaterialButtonRectangle();
        StuPnnel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        courses = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseDetails = new javax.swing.JTextArea();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        mediSID = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        MediTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        NoticeTbale = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        timeTablesView = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        Acourses = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ATTable = new javax.swing.JTable();
        PProgress = new javax.swing.JProgressBar();
        TProgress = new javax.swing.JProgressBar();
        Tpre = new javax.swing.JLabel();
        PPre = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        totProgress = new javax.swing.JProgressBar();
        totPre = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        TTTable = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ttmonday = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        tswed = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        tstues = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        tsfri = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        tsthus = new javax.swing.JTextArea();
        jLabel57 = new javax.swing.JLabel();
        tslevel = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        tslevel1 = new javax.swing.JLabel();
        tsdep = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        setID = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        setPhone = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        setAddress = new javax.swing.JTextField();
        setCity = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        setEmail = new javax.swing.JTextField();
        stClear = new javax.swing.JButton();
        stUpdate = new javax.swing.JButton();
        jLabel64 = new javax.swing.JLabel();
        CAMarks = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        CAMarksQz = new rojeru_san.complementos.RSTableMetro();
        jScrollPane15 = new javax.swing.JScrollPane();
        CAMarkasTable = new rojeru_san.complementos.RSTableMetro();
        jPanel2 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        gradeTable = new javax.swing.JTable();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtGPA = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/fot-logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 72, 67));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("University of Ruhuna");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 37, 250, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Faculty of Technology");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 11, 237, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/man-with-beard-avatar-character-isolated-icon-free-vector-removebg-preview-removebg-preview.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 89, 115, 100));

        adName.setBackground(new java.awt.Color(255, 255, 255));
        adName.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        adName.setForeground(new java.awt.Color(255, 255, 255));
        adName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adName.setText("B. Kavinda");
        jPanel1.add(adName, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 195, 240, -1));

        menutimetable.setBackground(new java.awt.Color(153, 0, 0));
        menutimetable.setText("GRADES & GPA");
        menutimetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menutimetableMouseClicked(evt);
            }
        });
        menutimetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutimetableActionPerformed(evt);
            }
        });
        jPanel1.add(menutimetable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, 54));

        menuuser.setBackground(new java.awt.Color(153, 0, 0));
        menuuser.setText("Course Details");
        menuuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuuserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuuserMouseEntered(evt);
            }
        });
        menuuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuuserActionPerformed(evt);
            }
        });
        jPanel1.add(menuuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 231, -1, 54));

        menucourse.setBackground(new java.awt.Color(153, 0, 0));
        menucourse.setText("Attendance");
        menucourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menucourseMouseClicked(evt);
            }
        });
        menucourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucourseActionPerformed(evt);
            }
        });
        jPanel1.add(menucourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 54));

        menunotice.setBackground(new java.awt.Color(153, 0, 0));
        menunotice.setText("Notices");
        menunotice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menunoticeMouseClicked(evt);
            }
        });
        menunotice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menunoticeActionPerformed(evt);
            }
        });
        jPanel1.add(menunotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 54));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/exit.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 539, 34, -1));

        jPanel6.setBackground(new java.awt.Color(255, 153, 0));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/profileSetting.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 50, 30));

        menutimetable1.setBackground(new java.awt.Color(153, 0, 0));
        menutimetable1.setText("Time Tables");
        menutimetable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menutimetable1MouseClicked(evt);
            }
        });
        menutimetable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutimetable1ActionPerformed(evt);
            }
        });
        jPanel1.add(menutimetable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, 54));

        menutimetable2.setBackground(new java.awt.Color(153, 0, 0));
        menutimetable2.setText("CA MARKS");
        menutimetable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menutimetable2MouseClicked(evt);
            }
        });
        menutimetable2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutimetable2ActionPerformed(evt);
            }
        });
        jPanel1.add(menutimetable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, 54));

        StuPnnel.setBackground(new java.awt.Color(255, 255, 255));
        StuPnnel.setLayout(new java.awt.CardLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/close.png"))); // NOI18N
        jLabel17.setText("jLabel17");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/minimize.png"))); // NOI18N
        jLabel32.setText("jLabel29");
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel15.setText("Student->Course Details->");

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(153, 0, 51));
        jLabel50.setText("View course details");

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 153, 0));
        jLabel48.setText("Select Course");

        courses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Course" }));
        courses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursesActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 51, 51));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("View");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        courseDetails.setColumns(20);
        courseDetails.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        courseDetails.setRows(5);
        courseDetails.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(courseDetails);

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(153, 0, 51));
        jLabel55.setText("View medical details");

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 153, 0));
        jLabel56.setText("Student ID");

        jButton8.setBackground(new java.awt.Color(255, 51, 51));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Clear");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        MediTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Refference ID", "Start Date", "End Date", "Course", "Status"
            }
        ));
        jScrollPane11.setViewportView(MediTable);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(337, 337, 337)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(courses, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel55)
                            .addComponent(jLabel50)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mediSID, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel32))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel50)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(courses, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel55)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mediSID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        StuPnnel.add(jPanel8, "card5");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Technical Officer Dashboard->");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/minimize.png"))); // NOI18N
        jLabel29.setText("jLabel29");
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/close.png"))); // NOI18N
        jLabel19.setText("jLabel18");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 153, 0));
        jLabel72.setText("Most Recent Notices");

        NoticeTbale.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NoticeTbale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Date", "Title", "View"
            }
        ));
        NoticeTbale.setGridColor(new java.awt.Color(255, 255, 255));
        NoticeTbale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NoticeTbaleMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(NoticeTbale);

        timeTablesView.setColumns(20);
        timeTablesView.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        timeTablesView.setRows(5);
        timeTablesView.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        timeTablesView.setEnabled(false);
        jScrollPane9.setViewportView(timeTablesView);

        jButton7.setBackground(new java.awt.Color(255, 0, 102));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Clear");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(271, 271, 271))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(261, 261, 261)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel72)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        StuPnnel.add(jPanel4, "card1");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel16.setText("Student ->Attendance->");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 255, 41));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(153, 0, 51));
        jLabel51.setText("View Attendance");
        jPanel3.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 79, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/minimize.png"))); // NOI18N
        jLabel33.setText("jLabel29");
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 11, 20, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/close.png"))); // NOI18N
        jLabel18.setText("jLabel17");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 11, 18, -1));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 153, 0));
        jLabel49.setText("Theory Attendance");
        jPanel3.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 317, -1, 22));

        Acourses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Course" }));
        Acourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcoursesActionPerformed(evt);
            }
        });
        jPanel3.add(Acourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 119, 206, 30));

        jButton6.setBackground(new java.awt.Color(255, 51, 51));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("View");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 119, 90, 30));

        ATTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Attendance ID", "Date", "Type", "Level", "Hourse"
            }
        ));
        jScrollPane2.setViewportView(ATTable);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 179, 610, 108));

        PProgress.setBackground(new java.awt.Color(255, 255, 255));
        PProgress.setForeground(new java.awt.Color(51, 153, 0));
        jPanel3.add(PProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 427, 345, 28));

        TProgress.setBackground(new java.awt.Color(255, 255, 255));
        TProgress.setForeground(new java.awt.Color(0, 153, 51));
        jPanel3.add(TProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 350, 345, 28));

        Tpre.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        Tpre.setText("Precentage 0.00%");
        jPanel3.add(Tpre, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 361, -1, -1));

        PPre.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        PPre.setText("Precentage 0.00%");
        jPanel3.add(PPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 438, -1, -1));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 153, 0));
        jLabel52.setText("Select Course");
        jPanel3.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 129, 86, 22));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 153, 0));
        jLabel53.setText("Practical Attendance");
        jPanel3.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 399, -1, 22));

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 153, 0));
        jLabel54.setText("Total Attendance");
        jPanel3.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 473, -1, 22));

        totProgress.setBackground(new java.awt.Color(255, 255, 255));
        totProgress.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        totProgress.setForeground(new java.awt.Color(204, 0, 0));
        jPanel3.add(totProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 501, 345, 28));

        totPre.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        totPre.setText("Precentage 0.00%");
        jPanel3.add(totPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 512, -1, -1));

        StuPnnel.add(jPanel3, "card2");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TTTable.setBackground(new java.awt.Color(255, 255, 255));
        TTTable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 51), new java.awt.Color(255, 0, 51), new java.awt.Color(255, 0, 51), new java.awt.Color(255, 0, 51)));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(153, 0, 51));
        jLabel46.setText("Level");
        jPanel10.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        ttmonday.setColumns(12);
        ttmonday.setFont(new java.awt.Font("Cambria", 1, 10)); // NOI18N
        ttmonday.setRows(5);
        jScrollPane3.setViewportView(ttmonday);

        jPanel10.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 232));

        tswed.setColumns(12);
        tswed.setFont(new java.awt.Font("Cambria", 1, 10)); // NOI18N
        tswed.setRows(5);
        jScrollPane5.setViewportView(tswed);

        jPanel10.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 110, 232));

        tstues.setColumns(12);
        tstues.setFont(new java.awt.Font("Cambria", 1, 10)); // NOI18N
        tstues.setRows(5);
        jScrollPane6.setViewportView(tstues);

        jPanel10.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 110, 232));

        tsfri.setColumns(12);
        tsfri.setFont(new java.awt.Font("Cambria", 1, 10)); // NOI18N
        tsfri.setRows(5);
        jScrollPane7.setViewportView(tsfri);

        jPanel10.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 110, 232));

        tsthus.setColumns(12);
        tsthus.setFont(new java.awt.Font("Cambria", 1, 10)); // NOI18N
        tsthus.setRows(5);
        jScrollPane8.setViewportView(tsthus);

        jPanel10.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 110, 232));

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(153, 0, 51));
        jLabel57.setText("Time tables");
        jPanel10.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        tslevel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tslevel.setForeground(new java.awt.Color(153, 0, 51));
        tslevel.setText("4");
        jPanel10.add(tslevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(153, 0, 51));
        jLabel58.setText("Semester");
        jPanel10.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        tslevel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tslevel1.setForeground(new java.awt.Color(153, 0, 51));
        tslevel1.setText("4");
        jPanel10.add(tslevel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        tsdep.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tsdep.setForeground(new java.awt.Color(153, 0, 51));
        tsdep.setText("BST");
        jPanel10.add(tsdep, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        TTTable.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 620, 440));

        jPanel5.add(TTTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 63, -1, 486));

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel5.setText("Student->Time table->");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 200, 41));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/minimize.png"))); // NOI18N
        jLabel30.setText("jLabel29");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 19, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/close.png"))); // NOI18N
        jLabel20.setText("jLabel18");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 18, -1));

        StuPnnel.add(jPanel5, "card3");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel21.setText("Student ->Setting->");

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/minimize.png"))); // NOI18N
        jLabel34.setText("jLabel29");
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/close.png"))); // NOI18N
        jLabel22.setText("jLabel17");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/man-with-beard-avatar-character-isolated-icon-free-vector-removebg-preview-removebg-preview.png"))); // NOI18N

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 153, 0));
        jLabel59.setText("Student ID");

        setID.setEnabled(false);

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 153, 0));
        jLabel60.setText("Phone No");

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 153, 0));
        jLabel61.setText("Address");

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 153, 0));
        jLabel62.setText("City");

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 153, 0));
        jLabel63.setText("Email");

        stClear.setBackground(new java.awt.Color(255, 51, 51));
        stClear.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        stClear.setForeground(new java.awt.Color(255, 255, 255));
        stClear.setText("Clear");
        stClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stClearMouseClicked(evt);
            }
        });

        stUpdate.setBackground(new java.awt.Color(255, 51, 51));
        stUpdate.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        stUpdate.setForeground(new java.awt.Color(255, 255, 255));
        stUpdate.setText("Update");
        stUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stUpdateMouseClicked(evt);
            }
        });

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(153, 0, 51));
        jLabel64.setText("Update Profile");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(347, 347, 347)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel64)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(53, 53, 53)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(setEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(setID, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(setCity, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(setAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(setPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(stClear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel22))
                .addGap(81, 81, 81)
                .addComponent(jLabel64)
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setCity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stClear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        StuPnnel.add(jPanel7, "card4");

        CAMarks.setBackground(new java.awt.Color(255, 255, 255));
        CAMarks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel23.setText("Student ->CA Marks->");
        CAMarks.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 255, 41));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/minimize.png"))); // NOI18N
        jLabel35.setText("jLabel29");
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });
        CAMarks.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 11, 20, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/close.png"))); // NOI18N
        jLabel24.setText("jLabel17");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        CAMarks.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 11, 18, -1));

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(153, 0, 51));
        jLabel65.setText("Eligibility");
        CAMarks.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(153, 0, 51));
        jLabel66.setText("CA Marks");
        CAMarks.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        CAMarksQz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject", "Quiz Marks", "Assesment Marks", "Mid"
            }
        ));
        CAMarksQz.setColorBackgoundHead(new java.awt.Color(255, 0, 51));
        CAMarksQz.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jScrollPane14.setViewportView(CAMarksQz);
        if (CAMarksQz.getColumnModel().getColumnCount() > 0) {
            CAMarksQz.getColumnModel().getColumn(0).setPreferredWidth(5);
            CAMarksQz.getColumnModel().getColumn(1).setPreferredWidth(5);
            CAMarksQz.getColumnModel().getColumn(2).setPreferredWidth(5);
            CAMarksQz.getColumnModel().getColumn(3).setPreferredWidth(5);
        }

        CAMarks.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 336, 590, 140));

        CAMarkasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject ID", "Course Name", "Status"
            }
        ));
        CAMarkasTable.setColorBackgoundHead(new java.awt.Color(255, 0, 51));
        CAMarkasTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jScrollPane15.setViewportView(CAMarkasTable);
        if (CAMarkasTable.getColumnModel().getColumnCount() > 0) {
            CAMarkasTable.getColumnModel().getColumn(0).setPreferredWidth(5);
            CAMarkasTable.getColumnModel().getColumn(1).setPreferredWidth(5);
            CAMarkasTable.getColumnModel().getColumn(2).setPreferredWidth(5);
        }

        CAMarks.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 111, 582, 140));

        StuPnnel.add(CAMarks, "card8");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel25.setText("Student ->Grades and GPA->");

        gradeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Subject Code", "Subject Name", "Marks", "Grade"
            }
        ));
        jScrollPane10.setViewportView(gradeTable);
        if (gradeTable.getColumnModel().getColumnCount() > 0) {
            gradeTable.getColumnModel().getColumn(0).setPreferredWidth(20);
            gradeTable.getColumnModel().getColumn(2).setPreferredWidth(20);
            gradeTable.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(153, 0, 51));
        jLabel67.setText("GPA");

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(153, 0, 51));
        jLabel68.setText("Grades");

        txtGPA.setColumns(12);
        txtGPA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtGPA.setRows(3);
        txtGPA.setDisabledTextColor(new java.awt.Color(255, 0, 51));
        txtGPA.setEnabled(false);
        jScrollPane12.setViewportView(txtGPA);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/close.png"))); // NOI18N
        jLabel27.setText("jLabel17");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/minimize.png"))); // NOI18N
        jLabel37.setText("jLabel29");
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel67)))
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(jLabel68)
                    .addContainerGap(534, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel27))
                .addGap(69, 69, 69)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel67)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(jLabel68)
                    .addContainerGap(498, Short.MAX_VALUE)))
        );

        StuPnnel.add(jPanel2, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(StuPnnel, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(StuPnnel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

public void student_on_load(){
    try {

            insert=conn1.prepareStatement("select * from student_course_module where stmod_st_id='"+userID+"'");
            ResultSet cID= insert.executeQuery();

            while(cID.next()){
                    String couseId = (String)cID.getString("stmod_cmod_id");
                    courses.addItem(couseId);
                    Acourses.addItem(couseId);

            }
            mediSID.setText(userID);
            insert=conn1.prepareStatement("select * from medical where med_st_id='"+userID+"'");
            ResultSet Medi= insert.executeQuery();
            DefaultTableModel df=(DefaultTableModel)MediTable.getModel();            

            df.setRowCount(0);
            while(Medi.next()){
                    Vector v1=new Vector();               
                    v1.add(Medi.getString("med_id"));
                    v1.add(Medi.getString("med_start_day"));
                    v1.add(Medi.getString("med_end_day"));
                    v1.add(Medi.getString("med_cmod_id"));
                    v1.add(Medi.getString("med_condition"));

                    df.addRow(v1);

            }


        } catch (SQLException ex) {
            Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
}
private void student_setting(){
     setID.setText(userID);
    try{

        insert=conn1.prepareStatement("select * from students where index_num='"+userID+"'");
        ResultSet rs=insert.executeQuery();
        insert=conn1.prepareStatement("select * from student_email where se_st_id='"+userID+"'");
        ResultSet getEmail=insert.executeQuery();
        while(rs.next()){
            setAddress.setText(rs.getString("address_l1"));
            setCity.setText(rs.getString("address_l2"));
            setPhone.setText(rs.getString("phone_num"));
            while(getEmail.next()){
                setEmail.setText(getEmail.getNString("se_email"));
            }
        }


    } catch (SQLException ex) {
            Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     }
}
private void notice_table_update(){
        StudentImp sImp = new StudentImp();

        List<Notice> list=sImp.List();
        DefaultTableModel df=(DefaultTableModel)NoticeTbale.getModel();
        df.setRowCount(0);

        for(Notice Nt: list){
            String NID=Nt.getNoticeId();
            String NDate=Nt.getNoticedate();
            String NTitle=Nt.getnoticeTitle();
            String Status="Download";
            df.addRow(new Object[]{NID,NDate,NTitle,Status});
    }

}
private void time_table(){

        try {
            insert=conn1.prepareStatement("select * from students where index_num='"+userID+"'");
            ResultSet stu=insert.executeQuery();
            TimeTable timeTable = new TimeTable();
            while(stu.next()){
                timeTable.setLevel(stu.getString("level"));
                timeTable.settSem(stu.getString("current_sem"));
                timeTable.settDepID(stu.getString("dep_id"));
            }
            insert=conn1.prepareStatement("select *  from time_table where Department_ID='"+timeTable.gettDepID()+"' and Level='"+timeTable.getLevel()+"' and Semester='"+timeTable.gettSem()+"' and Date='Monday'");
            ResultSet rs= insert.executeQuery();

            int a=1;
            ttmonday.append("Monday\n");
            while(rs.next()){
                timeTable.setS_name(rs.getString("Subject_Name"));
                timeTable.setS_time(rs.getString("Start_time"));
                timeTable.setE_time(rs.getString("End_time"));
                timeTable.setL_location(rs.getString("Location"));
                timeTable.setL_type(rs.getString("Type"));
                ttmonday.append("\n"+a+". "+timeTable.getS_name()+"\nTo-"+timeTable.getS_time()+"\nFrom-"+timeTable.getE_time()+"\n@"+timeTable.getL_location()+"\n"+"("+timeTable.getL_type()+")"+"\n--------------");
                a++;
            }
            insert=conn1.prepareStatement("select *  from time_table where Department_ID='"+timeTable.gettDepID()+"' and Level='"+timeTable.getLevel()+"' and Semester='"+timeTable.gettSem()+"' and Date='Tuesday'");
            ResultSet rs1= insert.executeQuery();

            a=1;
            tstues.append("Tuesday\n");
            while(rs1.next()){
                timeTable.setS_name(rs1.getString("Subject_Name"));
                timeTable.setS_time(rs1.getString("Start_time"));
                timeTable.setE_time(rs1.getString("End_time"));
                timeTable.setL_location(rs1.getString("Location"));
                timeTable.setL_type(rs1.getString("Type"));
                tstues.append("\n"+a+". "+timeTable.getS_name()+"\nTo-"+timeTable.getS_time()+"\nFrom-"+timeTable.getE_time()+"\n@"+timeTable.getL_location()+"\n"+"("+timeTable.getL_type()+")"+"\n--------------");
                a++;
            }

            insert=conn1.prepareStatement("select *  from time_table where Department_ID='"+timeTable.gettDepID()+"' and Level='"+timeTable.getLevel()+"' and Semester='"+timeTable.gettSem()+"' and Date='Wednesday'");
            ResultSet rs2= insert.executeQuery();

            a=1;
            tswed.append("Wednesday\n");
            while(rs2.next()){
                timeTable.setS_name(rs2.getString("Subject_Name"));
                timeTable.setS_time(rs2.getString("Start_time"));
                timeTable.setE_time(rs2.getString("End_time"));
                timeTable.setL_location(rs2.getString("Location"));
                timeTable.setL_type(rs2.getString("Type"));
                tswed.append("\n"+a+". "+timeTable.getS_name()+"\nTo-"+timeTable.getS_time()+"\nFrom-"+timeTable.getE_time()+"\n@"+timeTable.getL_location()+"\n"+"("+timeTable.getL_type()+")"+"\n--------------");
                a++;
            }
            insert=conn1.prepareStatement("select *  from time_table where Department_ID='"+timeTable.gettDepID()+"' and Level='"+timeTable.getLevel()+"' and Semester='"+timeTable.gettSem()+"' and Date='Thursday'");
            ResultSet rs3= insert.executeQuery();

            a=1;
            tsthus.append("Thursday\n");
            while(rs3.next()){
                timeTable.setS_name(rs3.getString("Subject_Name"));
                timeTable.setS_time(rs3.getString("Start_time"));
                timeTable.setE_time(rs3.getString("End_time"));
                timeTable.setL_location(rs3.getString("Location"));
                timeTable.setL_type(rs3.getString("Type"));  
                tsthus.append("\n"+a+". "+timeTable.getS_name()+"\nTo-"+timeTable.getS_time()+"\nFrom-"+timeTable.getE_time()+"\n@"+timeTable.getL_location()+"\n"+"("+timeTable.getL_type()+")"+"\n--------------");
                a++;
            }
            insert=conn1.prepareStatement("select *  from time_table where Department_ID='"+timeTable.gettDepID()+"' and Level='"+timeTable.getLevel()+"' and Semester='"+timeTable.gettSem()+"' and Date='Friday'");
            ResultSet rs4= insert.executeQuery();

            a=1;
            tsfri.append("Friday\n");
            while(rs4.next()){
                timeTable.setS_name(rs4.getString("Subject_Name"));
                timeTable.setS_time(rs4.getString("Start_time"));
                timeTable.setE_time(rs4.getString("End_time"));
                timeTable.setL_location(rs4.getString("Location"));
                timeTable.setL_type(rs4.getString("Type"));
                tsfri.append("\n"+a+". "+timeTable.getS_name()+"\nTo-"+timeTable.getS_time()+"\nFrom-"+timeTable.getE_time()+"\n@"+timeTable.getL_location()+"\n"+"("+timeTable.getL_type()+")"+"\n--------------");
                a++;
            }

        }catch (SQLException ex) {
            Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
}
private void time_table_clear(){
        ttmonday.setText("");
        tstues.setText("");
        tswed.setText("");
        tsthus.setText("");
        tsfri.setText("");
}


    private void menutimetableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menutimetableMouseClicked
                 caMarks CAM=new caMarks();        
        try {

            CID=conn1.prepareStatement("select *  from student_course_module where stmod_st_id='"+userID+"'");
            ResultSet CourseCode= CID.executeQuery();
            DefaultTableModel df=(DefaultTableModel)gradeTable.getModel();
            df.setRowCount(0);                                
            while(CourseCode.next()){
 
                    String CName="";
                    String CCode=CourseCode.getString("stmod_cmod_id");
                    insert=conn1.prepareStatement("select *  from course_module where cmod_id='"+CCode+"'");
                    ResultSet CourseName= insert.executeQuery();
                    while(CourseName.next()){
                       CName=CourseName.getString("cmod_name");

                    }
                    Vector v1=new Vector();
                    v1.add(CCode);
                    v1.add(CName);
                    CAM.calculateCA(userID,CCode);
                    double FinalCA=CAM.FinalCA();
                    double Marks=FinalCA+CAM.Fpractical()+CAM.Ftheory();
                    String grade=CAM.findGrade(Marks);
                    v1.add(formatter.format(Marks));
                    v1.add(grade);
                    df.addRow(v1);

            }
                double sum=0.00;
                if(gradeTable.getRowCount()>0){
                        int row = gradeTable.getRowCount();
                        int i;
                        
                        for(i=0;i<row;i++){

                            String marks =(String) gradeTable.getValueAt(i, 2);
                            double mark=Double.parseDouble(marks);
                            sum=sum+CAM.findGPA(mark);

                        }
                        txtGPA.append("Your GPA is :- ");
                        txtGPA.append(Float.toString((float) (sum/row)));

                    }
           

        } catch (SQLException ex) {
            Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }  
        cardLayout1.show(StuPnnel,"card7"); 
    }//GEN-LAST:event_menutimetableMouseClicked

    private void menutimetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutimetableActionPerformed
        cardLayout1.show(StuPnnel,"tcard4");
    }//GEN-LAST:event_menutimetableActionPerformed

    private void menuuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuuserMouseClicked
        student_on_load();
        cardLayout1.show(StuPnnel,"card5");
    }//GEN-LAST:event_menuuserMouseClicked

    private void menuuserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuuserMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_menuuserMouseEntered

    private void menuuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuuserActionPerformed

    }//GEN-LAST:event_menuuserActionPerformed

    private void menucourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menucourseMouseClicked
        cardLayout1.show(StuPnnel,"card2");
    }//GEN-LAST:event_menucourseMouseClicked

    private void menucourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucourseActionPerformed
        cardLayout1.show(StuPnnel,"CardPri3");
    }//GEN-LAST:event_menucourseActionPerformed

    private void menunoticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menunoticeActionPerformed
        cardLayout1.show(StuPnnel,"tcard5");
        //notice_table_update();
    }//GEN-LAST:event_menunoticeActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

        int dialogResult=JOptionPane.showConfirmDialog(null,"Do You Want to Exit?", "Warnning",JOptionPane.YES_NO_OPTION);

        if(dialogResult==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        student_setting();
        cardLayout1.show(StuPnnel,"card4");
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        int dialogResult=JOptionPane.showConfirmDialog(null,"Do You Want to Exit?", "Warnning",JOptionPane.YES_NO_OPTION);

        if(dialogResult==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel32MouseClicked

    private void coursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coursesActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        courseDetails.setText("");
        String CID=(String)courses.getSelectedItem();

    try {
 
            insert=conn1.prepareStatement("select *  from course_module where cmod_id='"+CID+"'");
            ResultSet rs= insert.executeQuery();
  
              while(rs.next()){ 
                    String lecID=rs.getString("cmod_lec_id");
                    insert=conn1.prepareStatement("select *  from lectures where lec_id='"+lecID+"'");
                    ResultSet lecname= insert.executeQuery();
                    while(lecname.next()){
                        courseDetails.append("Subject Code : -"+rs.getString("cmod_id")+"\nSubtect Name :-"+rs.getString("cmod_name")+"\nCredite :- "+rs.getString("cmod_credite")+" Course Conduct By "+rs.getString("cmod_dep_id")+" Department\nMarks are calculated As Quiz "+rs.getString("quiz_marks")+" Assesment "+rs.getString("assess_marks")+" \nMid "+rs.getString("mid_marks")+" Final Theory "+rs.getString("theory_marks")+" Final Patrical "+rs.getString("patrical_marks")+"\n--------------\nLecturer :-"+lecname.getString("f_name"));
                    }             
            }
            

        } catch (SQLException ex) {
            Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseClicked

    private void AcoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcoursesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcoursesActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        //courseDetails.setText("");
        String CID=(String)Acourses.getSelectedItem();
        try {

            insert=conn1.prepareStatement("select *  from attendance where atte_cmod_id='"+CID+"' and atte_st_id='"+userID+"'");
            ResultSet rs= insert.executeQuery();
  
            DefaultTableModel df=(DefaultTableModel)ATTable.getModel();            
            double tothourset = 0,tothoursep = 0,atothourset=0,atothoursep=0;

            PProgress.setVisible(false);
            jLabel53.setVisible(false);
            PPre.setVisible(false);

            TProgress.setVisible(false);
            jLabel49.setVisible(false);
            Tpre.setVisible(false);

            df.setRowCount(0);
            while(rs.next()){
                Vector v1=new Vector();
                    int Hourse=rs.getInt("Hourse");
                    String ACon=rs.getString("atte_condition");
                    int ALevel=rs.getInt("atte_level");             
                    v1.add(rs.getString("atte_id"));
                    v1.add(rs.getString("atte_date"));
                    v1.add(ACon);
                    v1.add(ALevel);
                    v1.add(Hourse);
                    if("T".equals(ACon)){
                        TProgress.setVisible(true);
                        jLabel49.setVisible(true);
                        Tpre.setVisible(true);
                        tothourset=tothourset+2;
                        if(ALevel==1){
                            atothourset=atothourset+2;
                         }
                     }else{
                        PProgress.setVisible(true);
                        jLabel53.setVisible(true);
                        PPre.setVisible(true);
                        tothoursep=tothoursep+3;
                        if(ALevel==1){
                            atothoursep=atothoursep+3;
                         }
                    }

                    df.addRow(v1);
             }
                double pTheory=(atothourset/tothourset)*100;
                double pPractical=(atothoursep/tothoursep)*100;
                double totattendance=(atothourset+atothoursep)/(tothourset+tothoursep)*100;

                    for(int i=0;i<=pTheory;i++){
                        TProgress.setValue(i);
                        
                        Tpre.setText("Precentage "+Integer.toString(i)+"%");
                        }

                    for(int i=0;i<=pPractical;i++){
                         PProgress.setValue(i);
                        PPre.setText("Precentage "+Integer.toString(i)+"%");
                    }

                    for(int i=0;i<=totattendance;i++){
                         totProgress.setValue(i);
                        totPre.setText("Precentage "+Integer.toString(i)+"%");
                        if(i>80){
                            totProgress.setStringPainted(true);
                            totProgress.setString("ELIGIBLE");
                        }else{
                            totProgress.setStringPainted(true);
                            totProgress.setString("NOT ELIGIBLE");
                            }
                    }



                } catch (SQLException ex) {
                    Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        int dialogResult=JOptionPane.showConfirmDialog(null,"Do You Want to Exit?", "Warnning",JOptionPane.YES_NO_OPTION);

        if(dialogResult==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel19MouseClicked

    private void NoticeTbaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoticeTbaleMouseClicked
        timeTablesView.setText("");
        DefaultTableModel df=(DefaultTableModel)NoticeTbale.getModel();
        int selectedIndex=NoticeTbale.getSelectedRow();
        String NoticeID=(df.getValueAt(selectedIndex, 0).toString());
        try {

            insert=conn1.prepareStatement("select *  from notice where Notice_ID='"+NoticeID+"'");
            ResultSet rs= insert.executeQuery();

            while(rs.next()){

                timeTablesView.append("\nDate :- "+rs.getString("DATE")+"\n"+rs.getString("Subject")+"\n\n"+rs.getString("Content")+"\n------------------------------------------------------------");
            }


        } catch (SQLException ex) {
            Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_NoticeTbaleMouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        timeTablesView.setText("");
    }//GEN-LAST:event_jButton7MouseClicked

    private void menunoticeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menunoticeMouseClicked
         cardLayout1.show(StuPnnel,"card1");
         notice_table_update();
    }//GEN-LAST:event_menunoticeMouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        int dialogResult=JOptionPane.showConfirmDialog(null,"Do You Want to Exit?", "Warnning",JOptionPane.YES_NO_OPTION);

        if(dialogResult==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseClicked

    private void stClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stClearMouseClicked
            setAddress.setText("");
            setCity.setText("");
            setPhone.setText("");
            setEmail.setText("");
    }//GEN-LAST:event_stClearMouseClicked

    private void stUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stUpdateMouseClicked
        try {

            String Address=setAddress.getText();
            String City=setCity.getText();
            String Email=setEmail.getText();
            String Telephone=setPhone.getText();


            insert=conn1.prepareStatement("update  students set address_l1=?,address_l2=?,phone_num=? where index_num='"+userID+"'");

            insert.setString(1,Address );
            insert.setString(2, City);           
            insert.setString(3,Telephone );

            update=conn1.prepareStatement("update  student_email set se_email=? where se_st_id='"+userID+"'");
            update.setString(1, Email);

            if( Address.isEmpty() || City.isEmpty() || Email.isEmpty() || Telephone.isEmpty()){
                    JOptionPane.showMessageDialog(this,"Please Fill the all the fields!!");
            }else{
                insert.executeUpdate();
                update.executeUpdate();

                JOptionPane.showMessageDialog(this,"Recode Update!!");
                student_setting();
            }      


        } catch (SQLException ex) {
             Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_stUpdateMouseClicked

    private void menutimetable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menutimetable1MouseClicked
        time_table_clear();        
        time_table();
        cardLayout1.show(StuPnnel,"card3");
    }//GEN-LAST:event_menutimetable1MouseClicked

    private void menutimetable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutimetable1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menutimetable1ActionPerformed

    private void menutimetable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menutimetable2MouseClicked
            caMarks CAM=new caMarks();        
        try {

            CID=conn1.prepareStatement("select *  from student_course_module where stmod_st_id='"+userID+"'");
            ResultSet CourseCode= CID.executeQuery();
            DefaultTableModel df=(DefaultTableModel)CAMarkasTable.getModel();
            DefaultTableModel Qdf=(DefaultTableModel)CAMarksQz.getModel();
                                             
           while(CourseCode.next()){
                    Vector v1=new Vector();
                    Vector v2=new Vector();
                   String CName="";
                    String CCode=CourseCode.getString("stmod_cmod_id");
                    insert=conn1.prepareStatement("select *  from course_module where cmod_id='"+CCode+"'");
                    ResultSet CourseName= insert.executeQuery();
                    while(CourseName.next()){
                       CName=CourseName.getString("cmod_name");
                    }
                    v1.add(CCode);
                    v1.add(CName);
                    v1.add(CAM.calculateCA(userID,CCode));
                    df.addRow(v1);

                    v2.add(CCode);
                    v2.add(CAM.QuizMarks());
                    v2.add(CAM.AssesMarks());
                    v2.add(CAM.MidMarks());
                    Qdf.addRow(v2);

                      
            }
           

        } catch (SQLException ex) {
            Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

            cardLayout1.show(StuPnnel,"card8");
            //CAmarks("CO 001","Pass");
    }//GEN-LAST:event_menutimetable2MouseClicked

    private void menutimetable2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutimetable2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menutimetable2ActionPerformed

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel37MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ATTable;
    private javax.swing.JComboBox<String> Acourses;
    private rojeru_san.complementos.RSTableMetro CAMarkasTable;
    private javax.swing.JPanel CAMarks;
    private rojeru_san.complementos.RSTableMetro CAMarksQz;
    private javax.swing.JTable MediTable;
    private javax.swing.JTable NoticeTbale;
    private javax.swing.JLabel PPre;
    private javax.swing.JProgressBar PProgress;
    private javax.swing.JPanel StuPnnel;
    private javax.swing.JProgressBar TProgress;
    private javax.swing.JPanel TTTable;
    private javax.swing.JLabel Tpre;
    private javax.swing.JLabel adName;
    private javax.swing.JTextArea courseDetails;
    private javax.swing.JComboBox<String> courses;
    private javax.swing.JTable gradeTable;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField mediSID;
    private rojerusan.RSMaterialButtonRectangle menucourse;
    private rojerusan.RSMaterialButtonRectangle menunotice;
    private rojerusan.RSMaterialButtonRectangle menutimetable;
    private rojerusan.RSMaterialButtonRectangle menutimetable1;
    private rojerusan.RSMaterialButtonRectangle menutimetable2;
    private rojerusan.RSMaterialButtonRectangle menuuser;
    private javax.swing.JTextField setAddress;
    private javax.swing.JTextField setCity;
    private javax.swing.JTextField setEmail;
    private javax.swing.JTextField setID;
    private javax.swing.JTextField setPhone;
    private javax.swing.JButton stClear;
    private javax.swing.JButton stUpdate;
    private javax.swing.JTextArea timeTablesView;
    private javax.swing.JLabel totPre;
    private javax.swing.JProgressBar totProgress;
    private javax.swing.JLabel tsdep;
    private javax.swing.JTextArea tsfri;
    private javax.swing.JLabel tslevel;
    private javax.swing.JLabel tslevel1;
    private javax.swing.JTextArea tsthus;
    private javax.swing.JTextArea tstues;
    private javax.swing.JTextArea tswed;
    private javax.swing.JTextArea ttmonday;
    private javax.swing.JTextArea txtGPA;
    // End of variables declaration//GEN-END:variables
}
