/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tecmis;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KA VI YA
 */
public class TechnicalOfficerDashboard extends javax.swing.JFrame {
    Connection conn1=ConnectDB.MyDBConnection();
    /**
     * Creates new form TechnicalOfficerDashboard
     */
    private static String userID;
    private static String depID;
    PreparedStatement insert;
    
    //ConnectDB myConnectDb = new ConnectDB();

    CardLayout cardLayout1;
    public TechnicalOfficerDashboard() {
        initComponents();
        notice_table_update();
        cardLayout1 =(CardLayout)(TechJPanel.getLayout());
    }

    public String getUser() {
        return userID;
    }

    /**
     *
     * @param aUser
     */
    public void setUser(String aUser) {
        userID = aUser;
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        adName = new javax.swing.JLabel();
        menutimetable = new rojerusan.RSMaterialButtonRectangle();
        menuuser = new rojerusan.RSMaterialButtonRectangle();
        menucourse = new rojerusan.RSMaterialButtonRectangle();
        menunotice = new rojerusan.RSMaterialButtonRectangle();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        TechJPanel = new javax.swing.JPanel();
        TNotice = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        NoticeTbale = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        timeTablesView = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        TTTable = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        timesub = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        tlevel = new javax.swing.JComboBox<>();
        jLabel49 = new javax.swing.JLabel();
        tsem = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        ttmonday = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        tswed = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        tstues = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        tsfri = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        tsthus = new javax.swing.JTextArea();
        jLabel50 = new javax.swing.JLabel();
        tslevel = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        tslevel1 = new javax.swing.JLabel();
        tsdep = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        TAttendances = new javax.swing.JPanel();
        txtAtStId = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtAtCmId = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        atDate = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        AtCon = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        AtStatus = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TOAttendanceTB = new javax.swing.JTable();
        jLabel38 = new javax.swing.JLabel();
        TSetting = new javax.swing.JPanel();
        txtFName = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        selGender = new javax.swing.JComboBox<>();
        txtLName = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        StUpdate = new rojerusan.RSMaterialButtonRectangle();
        jLabel15 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        TMedical = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtMedStId = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txtMedRef = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txtMedSDate = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        MedCond = new javax.swing.JComboBox<>();
        jLabel47 = new javax.swing.JLabel();
        txtMedEDate = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        txtMedCmId = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        MedTable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/fot-logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 72, 67));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("University of Ruhuna");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 37, 250, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Faculty of Technology");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 11, 237, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/man-with-beard-avatar-character-isolated-icon-free-vector-removebg-preview-removebg-preview.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 89, 115, 100));

        adName.setBackground(new java.awt.Color(255, 255, 255));
        adName.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        adName.setForeground(new java.awt.Color(255, 255, 255));
        adName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adName.setText("B. Kavinda");
        jPanel1.add(adName, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 195, 240, -1));

        menutimetable.setBackground(new java.awt.Color(153, 0, 0));
        menutimetable.setText("Time Tables");
        menutimetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menutimetableMouseClicked(evt);
            }
        });
        menutimetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutimetableActionPerformed(evt);
            }
        });
        jPanel1.add(menutimetable, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 440, -1, 54));

        menuuser.setBackground(new java.awt.Color(153, 0, 0));
        menuuser.setText("Update Attendance");
        menuuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuuserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuuserMouseEntered(evt);
            }
        });
        menuuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuuserActionPerformed(evt);
            }
        });
        jPanel1.add(menuuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 231, -1, 54));

        menucourse.setBackground(new java.awt.Color(153, 0, 0));
        menucourse.setText("Update Medical");
        menucourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menucourseMouseClicked(evt);
            }
        });
        menucourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucourseActionPerformed(evt);
            }
        });
        jPanel1.add(menucourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 54));

        menunotice.setBackground(new java.awt.Color(153, 0, 0));
        menunotice.setText("Notices");
        menunotice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menunoticeActionPerformed(evt);
            }
        });
        jPanel1.add(menunotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, 54));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/exit.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 539, 34, -1));

        jPanel6.setBackground(new java.awt.Color(255, 153, 0));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/profileSetting.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 50, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 622));

        TechJPanel.setBackground(new java.awt.Color(255, 255, 255));
        TechJPanel.setLayout(new java.awt.CardLayout());

        TNotice.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Technical Officer Dashboard->");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/minimize.png"))); // NOI18N
        jLabel29.setText("jLabel29");
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/close.png"))); // NOI18N
        jLabel18.setText("jLabel18");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 153, 0));
        jLabel72.setText("Most Recent Notices");

        NoticeTbale.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NoticeTbale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Date", "Title", "View"
            }
        ));
        NoticeTbale.setGridColor(new java.awt.Color(255, 255, 255));
        NoticeTbale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NoticeTbaleMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(NoticeTbale);

        timeTablesView.setColumns(20);
        timeTablesView.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        timeTablesView.setRows(5);
        timeTablesView.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        timeTablesView.setEnabled(false);
        jScrollPane9.setViewportView(timeTablesView);

        jButton6.setBackground(new java.awt.Color(255, 0, 102));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Clear");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel72)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(261, 261, 261))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout TNoticeLayout = new javax.swing.GroupLayout(TNotice);
        TNotice.setLayout(TNoticeLayout);
        TNoticeLayout.setHorizontalGroup(
            TNoticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TNoticeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TNoticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TNoticeLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        TNoticeLayout.setVerticalGroup(
            TNoticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TNoticeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TNoticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TNoticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(jLabel29))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        TechJPanel.add(TNotice, "tcard5");

        TTTable.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 51), new java.awt.Color(255, 0, 51), new java.awt.Color(255, 0, 51), new java.awt.Color(255, 0, 51)));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(153, 0, 51));
        jLabel46.setText("Level");
        jPanel10.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 178, -1, -1));

        jButton5.setBackground(new java.awt.Color(255, 51, 51));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Reset");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel10.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 90, 30));

        timesub.setBackground(new java.awt.Color(255, 51, 51));
        timesub.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        timesub.setForeground(new java.awt.Color(255, 255, 255));
        timesub.setText("Search");
        timesub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timesubMouseClicked(evt);
            }
        });
        timesub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timesubActionPerformed(evt);
            }
        });
        jPanel10.add(timesub, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 90, 30));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 153, 0));
        jLabel48.setText("Level");
        jPanel10.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 86, 22));

        tlevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        tlevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlevelActionPerformed(evt);
            }
        });
        jPanel10.add(tlevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 206, 30));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 153, 0));
        jLabel49.setText("Semester");
        jPanel10.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 86, 22));

        tsem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        tsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsemActionPerformed(evt);
            }
        });
        jPanel10.add(tsem, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 206, 30));

        ttmonday.setColumns(12);
        ttmonday.setFont(new java.awt.Font("Cambria", 1, 10)); // NOI18N
        ttmonday.setRows(5);
        jScrollPane3.setViewportView(ttmonday);

        jPanel10.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 213, 110, 232));

        tswed.setColumns(12);
        tswed.setFont(new java.awt.Font("Cambria", 1, 10)); // NOI18N
        tswed.setRows(5);
        jScrollPane5.setViewportView(tswed);

        jPanel10.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 110, 232));

        tstues.setColumns(12);
        tstues.setFont(new java.awt.Font("Cambria", 1, 10)); // NOI18N
        tstues.setRows(5);
        jScrollPane6.setViewportView(tstues);

        jPanel10.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 100, 232));

        tsfri.setColumns(12);
        tsfri.setFont(new java.awt.Font("Cambria", 1, 10)); // NOI18N
        tsfri.setRows(5);
        jScrollPane7.setViewportView(tsfri);

        jPanel10.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 110, 232));

        tsthus.setColumns(12);
        tsthus.setFont(new java.awt.Font("Cambria", 1, 10)); // NOI18N
        tsthus.setRows(5);
        jScrollPane8.setViewportView(tsthus);

        jPanel10.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 110, 232));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(153, 0, 51));
        jLabel50.setText("Time tables");
        jPanel10.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 11, -1, -1));

        tslevel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tslevel.setForeground(new java.awt.Color(153, 0, 51));
        tslevel.setText("4");
        jPanel10.add(tslevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 178, -1, -1));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(153, 0, 51));
        jLabel52.setText("Semester");
        jPanel10.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 178, -1, -1));

        tslevel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tslevel1.setForeground(new java.awt.Color(153, 0, 51));
        tslevel1.setText("4");
        jPanel10.add(tslevel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 178, -1, -1));

        tsdep.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tsdep.setForeground(new java.awt.Color(153, 0, 51));
        tsdep.setText("BST");
        jPanel10.add(tsdep, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 178, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel5.setText("Technical Officer Dashboard->Time table");

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/minimize.png"))); // NOI18N
        jLabel30.setText("jLabel29");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/close.png"))); // NOI18N
        jLabel19.setText("jLabel18");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TTTableLayout = new javax.swing.GroupLayout(TTTable);
        TTTable.setLayout(TTTableLayout);
        TTTableLayout.setHorizontalGroup(
            TTTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TTTableLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TTTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TTTableLayout.setVerticalGroup(
            TTTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TTTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TTTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TTTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jLabel30))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        TechJPanel.add(TTTable, "tcard4");

        TAttendances.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setText("Student ID");

        jLabel33.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel33.setText("Course ");

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/minimize.png"))); // NOI18N
        jLabel34.setText("jLabel29");
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/close.png"))); // NOI18N
        jLabel21.setText("jLabel17");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel16.setText("Technical Officer >Maintain Attendance->");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("Add Attendance");

        jLabel35.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel35.setText("Date");

        jLabel36.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel36.setText("Condition");

        AtCon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "T", "P" }));

        jLabel37.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel37.setText("Status");

        AtStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AtStatus.setText("Present");

        jButton1.setBackground(new java.awt.Color(255, 0, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Update");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reset");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        TOAttendanceTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Course", "Date", "Condition", "Status"
            }
        ));
        jScrollPane1.setViewportView(TOAttendanceTB);

        jLabel38.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(153, 153, 153));
        jLabel38.setText("T-Theory/P-Patrical");

        javax.swing.GroupLayout TAttendancesLayout = new javax.swing.GroupLayout(TAttendances);
        TAttendances.setLayout(TAttendancesLayout);
        TAttendancesLayout.setHorizontalGroup(
            TAttendancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TAttendancesLayout.createSequentialGroup()
                .addGroup(TAttendancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TAttendancesLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(TAttendancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(TAttendancesLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(TAttendancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(TAttendancesLayout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1))
                                    .addGroup(TAttendancesLayout.createSequentialGroup()
                                        .addGroup(TAttendancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel33)
                                            .addComponent(jLabel35)
                                            .addComponent(jLabel36)
                                            .addComponent(jLabel37))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(TAttendancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(atDate, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAtStId, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAtCmId, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(TAttendancesLayout.createSequentialGroup()
                                                .addComponent(AtCon, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel38))
                                            .addComponent(AtStatus)))))))
                    .addGroup(TAttendancesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(TAttendancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(TAttendancesLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(250, 250, 250)
                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        TAttendancesLayout.setVerticalGroup(
            TAttendancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TAttendancesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TAttendancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jLabel21)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(32, 32, 32)
                .addGroup(TAttendancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAtStId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TAttendancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAtCmId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TAttendancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TAttendancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(TAttendancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AtCon)
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TAttendancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(AtStatus))
                .addGap(18, 18, 18)
                .addGroup(TAttendancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261))
        );

        TechJPanel.add(TAttendances, "tcard2");

        TSetting.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setText("First Name");

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/man-with-beard-avatar-character-isolated-icon-free-vector-removebg-preview-removebg-preview.png"))); // NOI18N
        jLabel31.setText("jLabel31");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Gender");

        selGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("Last Name");

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setText("Adress Line 1");

        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setText("Adress Line 2");

        jLabel27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel27.setText("Date of Birth");

        jLabel28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel28.setText("Phone Number");

        StUpdate.setText("Update");
        StUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StUpdateActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel15.setText("Technical Officer >Setting->");

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/minimize.png"))); // NOI18N
        jLabel32.setText("jLabel29");
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/close.png"))); // NOI18N
        jLabel17.setText("jLabel17");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TSettingLayout = new javax.swing.GroupLayout(TSetting);
        TSetting.setLayout(TSettingLayout);
        TSettingLayout.setHorizontalGroup(
            TSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TSettingLayout.createSequentialGroup()
                .addGroup(TSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TSettingLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(345, 345, 345)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TSettingLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(TSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TSettingLayout.createSequentialGroup()
                                .addGroup(TSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(TSettingLayout.createSequentialGroup()
                                        .addGroup(TSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel27)
                                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel28))
                                        .addGap(24, 24, 24)
                                        .addGroup(TSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(selGender, 0, 200, Short.MAX_VALUE)
                                            .addGroup(TSettingLayout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addGap(30, 30, 30)
                                .addComponent(StUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addGroup(TSettingLayout.createSequentialGroup()
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(TSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(TSettingLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(TSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel23)
                                            .addGroup(TSettingLayout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(jLabel22))))
                                    .addGroup(TSettingLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TSettingLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        TSettingLayout.setVerticalGroup(
            TSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TSettingLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(TSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(TSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TSettingLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel31))
                    .addGroup(TSettingLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(TSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TSettingLayout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TSettingLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selGender, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TechJPanel.add(TSetting, "tcard1");

        TMedical.setBackground(new java.awt.Color(255, 255, 255));

        jLabel39.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel39.setText("Technical Officer >Maintain Medical->");

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/minimize.png"))); // NOI18N
        jLabel40.setText("jLabel29");
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
        });

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/close.png"))); // NOI18N
        jLabel41.setText("jLabel17");
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel41MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 0));
        jLabel10.setText("Add Medical");

        jLabel42.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel42.setText("Student ID");

        jLabel43.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel43.setText("Medical Refference");

        jLabel44.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel44.setText("Start Date");

        jLabel45.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel45.setText("Condition");

        MedCond.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Approved", "Reject" }));

        jLabel47.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel47.setText("End Date");

        jLabel51.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel51.setText("Course ID");

        MedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Medical Ref", "Student ID", "Course", "Start date", "End Date", "Condition"
            }
        ));
        MedTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(MedTable);

        jButton3.setBackground(new java.awt.Color(255, 0, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Update");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 0, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Add");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 0, 102));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Reset");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 0));
        jLabel11.setText("Medical Details");

        javax.swing.GroupLayout TMedicalLayout = new javax.swing.GroupLayout(TMedical);
        TMedical.setLayout(TMedicalLayout);
        TMedicalLayout.setHorizontalGroup(
            TMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TMedicalLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(TMedicalLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(TMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TMedicalLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(TMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(TMedicalLayout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4))
                            .addGroup(TMedicalLayout.createSequentialGroup()
                                .addGroup(TMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel42)
                                    .addComponent(jLabel43)
                                    .addComponent(jLabel44)
                                    .addComponent(jLabel47)
                                    .addComponent(jLabel51)
                                    .addComponent(jLabel45))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(TMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMedCmId, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedEDate, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedSDate, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedStId, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedRef, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MedCond, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        TMedicalLayout.setVerticalGroup(
            TMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TMedicalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(32, 32, 32)
                .addGroup(TMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedStId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedRef, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedSDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedEDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedCmId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MedCond, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(TMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        TechJPanel.add(TMedical, "tcard3");

        getContentPane().add(TechJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 0, 670, 622));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void technical_officer_setting(){
    int c;
    try {

            insert=conn1.prepareStatement("select *  from technical_officers where to_id='"+userID+"'");
            ResultSet rs= insert.executeQuery();
            ResultSetMetaData Rss=rs.getMetaData();
            c=Rss.getColumnCount();

            while(rs.next()){
                for(int a=1;a<c;a++){
                    txtFName.setText(rs.getString("f_name"));
                    txtLName.setText(rs.getString("l_name"));
                    txtAddress.setText(rs.getString("address_l1"));
                    txtCity.setText(rs.getString("address_l2"));

                    String gen = (String)rs.getString("gender");
                    //selGender.addItem(gen);
                    selGender.setSelectedItem(gen);

                    txtDOB.setText(rs.getString("dob"));
                    txtPhone.setText(rs.getString("phone_num")); 

 
                }
            }


        } catch (SQLException ex) {
            Logger.getLogger(TechnicalOfficerDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

}
private void attendance_table_update(){
    int c;
    try {

            insert=conn1.prepareStatement("select *  from attendance");
            ResultSet rs= insert.executeQuery();
            ResultSetMetaData Rss=rs.getMetaData();
            c=Rss.getColumnCount();

            DefaultTableModel df=(DefaultTableModel)TOAttendanceTB.getModel();

            df.setRowCount(0);
            while(rs.next()){
                Vector v2=new Vector();
                for(int a=1;a<c;a++){
                    v2.add(rs.getString("atte_st_id"));
                    v2.add(rs.getString("atte_cmod_id"));
                    v2.add(rs.getString("atte_date"));
                    v2.add(rs.getString("atte_condition"));
                    v2.add(rs.getString("atte_level"));
                }
                    df.addRow(v2);
            }


        } catch (SQLException ex) {
            Logger.getLogger(TechnicalOfficerDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

} 
private void medical_table_update(){
    int c;
    try {

            insert=conn1.prepareStatement("select *  from medical");
            ResultSet rs= insert.executeQuery();
            ResultSetMetaData Rss=rs.getMetaData();
            c=Rss.getColumnCount();

            DefaultTableModel df=(DefaultTableModel)MedTable.getModel();

            df.setRowCount(0);
            while(rs.next()){
                Vector v2=new Vector();
                for(int a=1;a<c;a++){
                    v2.add(rs.getString("med_id"));
                    v2.add(rs.getString("med_st_id"));
                    v2.add(rs.getString("med_cmod_id"));
                    v2.add(rs.getString("med_start_day"));
                    v2.add(rs.getString("med_end_day"));
                    v2.add(rs.getString("med_condition"));
                }
                    df.addRow(v2);
            }


        } catch (SQLException ex) {
            Logger.getLogger(TechnicalOfficerDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

}             
    private void menutimetableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menutimetableMouseClicked
       try {

            insert=conn1.prepareStatement("select dep_id  from technical_officers where to_id='"+userID+"'");
            ResultSet rs= insert.executeQuery();
  
            while(rs.next()){          
                   depID=rs.getString("dep_id");
             }


        } catch (SQLException ex) {
            Logger.getLogger(TechnicalOfficerDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menutimetableMouseClicked

    private void menutimetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutimetableActionPerformed
         cardLayout1.show(TechJPanel,"tcard4");
    }//GEN-LAST:event_menutimetableActionPerformed
private void notice_table_update(){
    try {
 
            insert=conn1.prepareStatement("select *  from notice");
            ResultSet rs= insert.executeQuery();
  
            DefaultTableModel df=(DefaultTableModel)NoticeTbale.getModel();            

            df.setRowCount(0);
            while(rs.next()){
                Vector v1=new Vector();               
                    v1.add(rs.getString("Notice_ID"));
                    v1.add(rs.getString("DATE"));
                    v1.add(rs.getString("Subject"));
                    v1.add("Download");

                    df.addRow(v1);
             }


        } catch (SQLException ex) {
            Logger.getLogger(TechnicalOfficerDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    private void menuuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuuserActionPerformed

    }//GEN-LAST:event_menuuserActionPerformed

    private void menucourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucourseActionPerformed
        cardLayout1.show(TechJPanel,"CardPri3");
    }//GEN-LAST:event_menucourseActionPerformed

    private void menunoticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menunoticeActionPerformed
        cardLayout1.show(TechJPanel,"tcard5");
        notice_table_update();
    }//GEN-LAST:event_menunoticeActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

        int dialogResult=JOptionPane.showConfirmDialog(null,"Do You Want to Exit?", "Warnning",JOptionPane.YES_NO_OPTION);

        if(dialogResult==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        technical_officer_setting();
        cardLayout1.show(TechJPanel,"tcard1");
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        int dialogResult=JOptionPane.showConfirmDialog(null,"Do You Want to Exit?", "Warnning",JOptionPane.YES_NO_OPTION);

        if(dialogResult==JOptionPane.YES_NO_OPTION){    
                System.exit(0);
        }
    }//GEN-LAST:event_jLabel18MouseClicked

    private void NoticeTbaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoticeTbaleMouseClicked
        timeTablesView.setText("");
        DefaultTableModel df=(DefaultTableModel)NoticeTbale.getModel();
        int selectedIndex=NoticeTbale.getSelectedRow();
        String NoticeID=(df.getValueAt(selectedIndex, 0).toString());
        try {

            insert=conn1.prepareStatement("select *  from notice where Notice_ID='"+NoticeID+"'");
            ResultSet rs= insert.executeQuery();

            while(rs.next()){

                timeTablesView.append("\nDate :- "+rs.getString("DATE")+"\n"+rs.getString("Subject")+"\n\n"+rs.getString("Content")+"\n------------------------------------------------------------");
            }

        } catch (SQLException ex) {
            Logger.getLogger(TechnicalOfficerDashboard.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_NoticeTbaleMouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        timeTablesView.setText("");
    }//GEN-LAST:event_jButton6MouseClicked
private void time_table_clear(){
        ttmonday.setText("");
        tstues.setText("");
        tswed.setText("");
        tsthus.setText("");
        tsfri.setText("");
}
    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        time_table_clear();
    }//GEN-LAST:event_jButton5MouseClicked

    private void timesubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timesubMouseClicked
        time_table_clear();
        String tDepID=depID;
        String Level=(String)tlevel.getSelectedItem();
        String tSem=(String)tsem.getSelectedItem();
        try {

            insert=conn1.prepareStatement("select *  from time_table where Department_ID='"+tDepID+"' and Level='"+Level+"' and Semester='"+tSem+"' and Date='Monday'");
            ResultSet rs= insert.executeQuery();

            int a=1;
            ttmonday.append("Monday\n");
            while(rs.next()){
                ttmonday.append("\n"+a+". "+rs.getString("Subject_Name")+"\nTo-"+rs.getString("Start_time")+"\nFrom-"+rs.getString("End_time")+"\n@"+rs.getString("Location")+"\n"+"("+rs.getString("Type")+")"+"\n--------------");
                a++;
            }
            insert=conn1.prepareStatement("select *  from time_table where Department_ID='"+tDepID+"' and Level='"+Level+"' and Semester='"+tSem+"' and Date='Tuesday'");
            ResultSet rs1= insert.executeQuery();

            a=1;
            tstues.append("Tuesday\n");
            while(rs1.next()){
                tstues.append("\n"+a+". "+rs1.getString("Subject_Name")+"\nTo-"+rs1.getString("Start_time")+"\nFrom-"+rs1.getString("End_time")+"\n@"+rs1.getString("Location")+"\n"+"("+rs1.getString("Type")+")"+"\n--------------");
                a++;
            }

            insert=conn1.prepareStatement("select *  from time_table where Department_ID='"+tDepID+"' and Level='"+Level+"' and Semester='"+tSem+"' and Date='Wednesday'");
            ResultSet rs2= insert.executeQuery();

            a=1;
            tswed.append("Wednesday\n");
            while(rs2.next()){
                tswed.append("\n"+a+". "+rs2.getString("Subject_Name")+"\nTo-"+rs2.getString("Start_time")+"\nFrom-"+rs2.getString("End_time")+"\n@"+rs2.getString("Location")+"\n"+"("+rs2.getString("Type")+")"+"\n--------------");
                a++;
            }
            insert=conn1.prepareStatement("select *  from time_table where Department_ID='"+tDepID+"' and Level='"+Level+"' and Semester='"+tSem+"' and Date='Thursday'");
            ResultSet rs3= insert.executeQuery();

            a=1;
            tsthus.append("Thursday\n");
            while(rs3.next()){
                tsthus.append("\n"+a+". "+rs3.getString("Subject_Name")+"\nTo-"+rs3.getString("Start_time")+"\nFrom-"+rs3.getString("End_time")+"\n@"+rs3.getString("Location")+"\n"+"("+rs3.getString("Type")+")"+"\n--------------");
                a++;
            }
            insert=conn1.prepareStatement("select *  from time_table where Department_ID='"+tDepID+"' and Level='"+Level+"' and Semester='"+tSem+"' and Date='Friday'");
            ResultSet rs4= insert.executeQuery();

            a=1;
            tsfri.append("Friday\n");
            while(rs4.next()){
                tsfri.append("\n"+a+". "+rs4.getString("Subject_Name")+"\nTo-"+rs4.getString("Start_time")+"\nFrom-"+rs4.getString("End_time")+"\n@"+rs4.getString("Location")+"\n"+"("+rs4.getString("Type")+")"+"\n--------------");
                a++;
            }

        } catch (SQLException ex) {
            //Logger.getLogger(TechnicalOfficerDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_timesubMouseClicked

    private void timesubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timesubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timesubActionPerformed

    private void tlevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlevelActionPerformed

    private void tsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsemActionPerformed

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
       this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
       int dialogResult=JOptionPane.showConfirmDialog(null,"Do You Want to Exit?", "Warnning",JOptionPane.YES_NO_OPTION);

        if(dialogResult==JOptionPane.YES_NO_OPTION){    
                System.exit(0);
        }
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        int dialogResult=JOptionPane.showConfirmDialog(null,"Do You Want to Exit?", "Warnning",JOptionPane.YES_NO_OPTION);

        if(dialogResult==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void StUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StUpdateActionPerformed

        try {
            String FName=txtFName.getText();
            String LName=txtLName.getText();
            String Address=txtAddress.getText();
            String City=txtCity.getText();
            String Gender=(String)selGender.getSelectedItem();
            String DOB=txtDOB.getText();
            String Telephone=txtPhone.getText();


            insert=conn1.prepareStatement("update  technical_officers set f_name=?,l_name=?,address_l1=?,address_l2=?,gender=?,dob=?,phone_num=? where to_id='"+userID+"'");

            insert.setString(1, FName);
            insert.setString(2, LName);
            insert.setString(3,Address );
            insert.setString(4, City);
            insert.setString(5, Gender);
            insert.setString(6, DOB);
            insert.setString(7,Telephone );

        if(FName.isEmpty() || LName.isEmpty() || Address.isEmpty() || City.isEmpty() || Gender.isEmpty() || DOB.isEmpty() || Telephone.isEmpty()){
                JOptionPane.showMessageDialog(this,"Please Fill the all the fields!!");
        }else{
            insert.executeUpdate();

            JOptionPane.showMessageDialog(this,"Recode Update!!");
            technical_officer_setting();
        }      


        } catch (SQLException ex) {
            Logger.getLogger(TechnicalOfficerDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_StUpdateActionPerformed

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
       int dialogResult=JOptionPane.showConfirmDialog(null,"Do You Want to Exit?", "Warnning",JOptionPane.YES_NO_OPTION);

        if(dialogResult==JOptionPane.YES_NO_OPTION){    
                System.exit(0);
        }
    }//GEN-LAST:event_jLabel21MouseClicked

    private void menuuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuuserMouseClicked
        attendance_table_update();
        cardLayout1.show(TechJPanel,"tcard2");
    }//GEN-LAST:event_menuuserMouseClicked
private void clear_addAttendance_fields(){
            txtAtStId.setText("");
            txtAtCmId.setText("");
            atDate.setText("");
            AtCon.setSelectedIndex(0);
            AtStatus.setSelected(false);
}
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
            String SID=txtAtStId.getText();
            String CID=txtAtCmId.getText();
            String ADate=atDate.getText();
            String CLevel=(String)AtCon.getSelectedItem();

        int p;
        if(this.AtStatus.isSelected()){
                p =1;
            } else {
                p = 0;
            }    

            try {

            insert=conn1.prepareStatement("insert into attendance(atte_st_id,atte_cmod_id,atte_date,atte_condition,atte_level) values (?,?,?,?,?)");
            insert.setString(1, SID);
            insert.setString(2, CID);
            insert.setString(3, ADate);
            insert.setString(4,CLevel );
            insert.setInt(5,p);

            if(SID.isEmpty() || CID.isEmpty() || ADate.isEmpty() ){

                JOptionPane.showMessageDialog(this,"Please fill the all the fields");
               
            }else{
                insert.executeUpdate();
                JOptionPane.showMessageDialog(this,"Course is Added!!");
                clear_addAttendance_fields();
            }
            

        } catch (SQLException ex) {
            Logger.getLogger(TechnicalOfficerDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        clear_addAttendance_fields();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel40MouseClicked

    private void jLabel41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseClicked
        int dialogResult=JOptionPane.showConfirmDialog(null,"Do You Want to Exit?", "Warnning",JOptionPane.YES_NO_OPTION);

        if(dialogResult==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel41MouseClicked
private void clear_add_medical(){
            txtMedStId.setText("");
            txtMedCmId.setText("");
            txtMedRef.setText("");
            txtMedSDate.setText("");
            txtMedEDate.setText("");
            MedCond.setSelectedIndex(0);
}
    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
            String SID=txtMedStId.getText();
            String CID=txtMedCmId.getText();
            String Mref=txtMedRef.getText();
            String Sdate=txtMedSDate.getText();
            String Edate=txtMedEDate.getText();
            String Medcon=(String)MedCond.getSelectedItem();


            try {

            insert=conn1.prepareStatement("insert into medical(med_id ,med_start_day,med_end_day,med_st_id,med_cmod_id,med_condition) values (?,?,?,?,?,?)");
            insert.setString(1, Mref);
            insert.setString(2, Sdate);
            insert.setString(3, Edate);
            insert.setString(4,SID );
            insert.setString(5,CID );
            insert.setString(6,Medcon );

            if(SID.isEmpty() || CID.isEmpty() || Mref.isEmpty() || Sdate.isEmpty() || Edate.isEmpty() ){

                JOptionPane.showMessageDialog(this,"Please fill the all the fields");
               
            }else{
                insert.executeUpdate();
                JOptionPane.showMessageDialog(this,"Medical is Added!!");
                clear_add_medical();
            }
            

        } catch (SQLException ex) {
            Logger.getLogger(TechnicalOfficerDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void menucourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menucourseMouseClicked
        medical_table_update();        
        cardLayout1.show(TechJPanel,"tcard3");
    }//GEN-LAST:event_menucourseMouseClicked

    private void menuuserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuuserMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_menuuserMouseEntered

    private void MedTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedTableMouseClicked
            DefaultTableModel df=(DefaultTableModel)MedTable.getModel();
            int selectedIndex=MedTable.getSelectedRow();
            txtMedRef.setText(df.getValueAt(selectedIndex, 0).toString());
            txtMedStId.setText(df.getValueAt(selectedIndex, 1).toString());
            txtMedCmId.setText(df.getValueAt(selectedIndex, 2).toString());
            txtMedSDate.setText(df.getValueAt(selectedIndex, 3).toString());
            txtMedEDate.setText(df.getValueAt(selectedIndex, 4).toString());

            String cond = (String)df.getValueAt(selectedIndex, 5).toString();
            //selGender.addItem(gen);
            MedCond.setSelectedItem(cond);

    }//GEN-LAST:event_MedTableMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        try {
        //int id=Integer.parseInt(df.getValueAt(selectedIndex,0).toString());

            String SID=txtMedStId.getText();
            String CID=txtMedCmId.getText();
            String Mref=txtMedRef.getText();
            String Sdate=txtMedSDate.getText();
            String Edate=txtMedEDate.getText();
            String Medcon=(String)MedCond.getSelectedItem();


            insert=conn1.prepareStatement("update  medical set med_id =?,med_start_day	=?,med_end_day=?,med_st_id=?,med_cmod_id=?,med_condition=? where med_id=?");
            insert.setString(1, Mref);
            insert.setString(2, Sdate);
            insert.setString(3, Edate);
            insert.setString(4,SID );
            insert.setString(5,CID );
            insert.setString(6,Medcon );
            insert.setString(7, Mref);

            if(SID.isEmpty() || CID.isEmpty() || Mref.isEmpty() || Sdate.isEmpty() || Edate.isEmpty() ){

                JOptionPane.showMessageDialog(this,"Please fill the all the fields");
               
            }else{
                insert.executeUpdate();
                JOptionPane.showMessageDialog(this,"Recode Updated!!");
                medical_table_update();
                clear_add_medical();
            }
            


        } catch (SQLException ex) {
            Logger.getLogger(TechnicalOfficerDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        clear_add_medical();
    }//GEN-LAST:event_jButton7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TechnicalOfficerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TechnicalOfficerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TechnicalOfficerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TechnicalOfficerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TechnicalOfficerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AtCon;
    private javax.swing.JCheckBox AtStatus;
    private javax.swing.JComboBox<String> MedCond;
    private javax.swing.JTable MedTable;
    private javax.swing.JTable NoticeTbale;
    private rojerusan.RSMaterialButtonRectangle StUpdate;
    private javax.swing.JPanel TAttendances;
    private javax.swing.JPanel TMedical;
    private javax.swing.JPanel TNotice;
    private javax.swing.JTable TOAttendanceTB;
    private javax.swing.JPanel TSetting;
    private javax.swing.JPanel TTTable;
    private javax.swing.JPanel TechJPanel;
    private javax.swing.JLabel adName;
    private javax.swing.JTextField atDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private rojerusan.RSMaterialButtonRectangle menucourse;
    private rojerusan.RSMaterialButtonRectangle menunotice;
    private rojerusan.RSMaterialButtonRectangle menutimetable;
    private rojerusan.RSMaterialButtonRectangle menuuser;
    private javax.swing.JComboBox<String> selGender;
    private javax.swing.JTextArea timeTablesView;
    private javax.swing.JButton timesub;
    private javax.swing.JComboBox<String> tlevel;
    private javax.swing.JLabel tsdep;
    private javax.swing.JComboBox<String> tsem;
    private javax.swing.JTextArea tsfri;
    private javax.swing.JLabel tslevel;
    private javax.swing.JLabel tslevel1;
    private javax.swing.JTextArea tsthus;
    private javax.swing.JTextArea tstues;
    private javax.swing.JTextArea tswed;
    private javax.swing.JTextArea ttmonday;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAtCmId;
    private javax.swing.JTextField txtAtStId;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtMedCmId;
    private javax.swing.JTextField txtMedEDate;
    private javax.swing.JTextField txtMedRef;
    private javax.swing.JTextField txtMedSDate;
    private javax.swing.JTextField txtMedStId;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
